# 16-char cmds

"MEDIMG_CMDS": 

  # Medical Image Plan module commands
  {
    "START_AUTO_DIGITIZE": "start_autodigitz",
    "START_REGISTRATION": "start_registrati",
    "START_USE_PREV_REGISTRATION": "start_useprevreg",
    "FIDUCIAL_CURRENT_ON_IMG": "img_fid_pntxxxxx",
    "FIDUCIAL_NUM_OF_ON_IMG": "img_fid_numxxxxx",
    "TARGET_POSE_ORIENTATION": "target_rotxxxxxx",
    "TARGET_POSE_TRANSLATION": "target_tslxxxxxx",
  }

"ROBCTRL_CMDS":

  # Robot Control module commands
  {
    "GET_JNT_ANGS": "get_jnt_angsxxxx",
    "GET_EFF_POSE": "get_eff_posexxxx",
    "EXECUTE_MOTION": "execute_motionxx",
    "EXECUTE_MOVE_CONFIRM": "execute_confirmx",
    "SESSION_END": "end_sessionxxxxx",
    "MAN_ADJUST_BACKWARD": "adjust_backxxxxx",
    "MAN_ADJUST_CLOSER": "adjust_closexxxx",
    "MAN_ADJUST_FARTHER": "adjust_awayxxxxx",
    "MAN_ADJUST_FORWARD": "adjust_forwxxxxx",
    "MAN_ADJUST_LEFT": "adjust_leftxxxxx",
    "MAN_ADJUST_PITCH": "adjust_pitchxxxx",
    "MAN_ADJUST_RIGHT": "adjust_rightxxxx",
    "MAN_ADJUST_ROLL": "adjust_rollxxxxx",
    "MAN_ADJUST_YAW": "adjust_yawxxxxxx"
  }

"TARGETVIZ_CMDS":

  # Target Visualization module commands
  {
    "VISUALIZE_START": "start_visualizex",
    "VISUALIZE_STOP": "stop_visualizexx"
  }
