# 16-char cmds

"MEDIMG_CMDS": 

  # Medical Image Plan module commands
  {
    "START_AUTO_DIGITIZE": "start_autodigitz",
    "START_REGISTRATION": "start_registrati",
    "START_USE_PREV_REGISTRATION": "start_useprevreg",

    "LANDMARK_CURRENT_ON_IMG": "img_fid_pntxxxxx",
    "LANDMARK_NUM_OF_ON_IMG": "img_fid_numxxxxx",
    "LANDMARK_LAST_RECEIVED": "img_fig_lastrecv",

    "TARGET_POSE_ORIENTATION": "target_rotxxxxxx",
    "TARGET_POSE_TRANSLATION": "target_tslxxxxxx",
  }

"ROBCTRL_CMDS":

  # Robot Control module commands
  {
    "GET_JNT_ANGS": "get_jnt_angsxxxx",
    "GET_EFF_POSE": "get_eff_posexxxx",

    "EXECUTE_MOTION": "execute_motionxx",
    "EXECUTE_MOVE_CONFIRM": "execute_confirmx",
    "EXECUTE_ENDBACK": "end_session_back",
    "EXECUTE_BACKINIT": "execute_backinit",
    "EXECUTE_BACKOFFSET": "execute_bkoffset",

    "SESSION_END": "end_sessionxxxxx",
    
    "MAN_ADJUST_T": "adjust_tranxxxxx",
    "MAN_ADJUST_R": "adjust_oriexxxxx",

    "ROB_CONN_ON": "rob_conn_onxxxxx",
    "ROB_CONN_OFF": "rob_conn_offxxxx"
  }

"TARGETVIZ_CMDS":

  # Target Visualization module commands
  {
    "VISUALIZE_START": "start_visualizex",
    "VISUALIZE_STOP": "stop_visualizexx"
  }
